# .travis.yml for Frontend (ReactJS)

language: node_js
node_js:
  - "16"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run build
  - npm test -- --coverage

deploy:
  provider: script
  script: bash scripts/deploy.sh  # Ejemplo de script de despliegue personalizado
  on:
    branch: main
